import type React from "react"
import Header from "@/components/header"
import { ThemeProvider } from "@/components/ThemeProvider"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.dev",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          {" "}
          <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
              <body className={`${inter.className} antialiased w-full h-full`}>
                {/* <AppBar /> */}
                {/* <DashboardSidebar>{children}</DashboardSidebar> */}
                {/* <LandingPage></LandingPage> */}
                <Header />

                {children}
              </body>
            </html>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

import "./globals.css"



import './globals.css'